import os
import numpy as np
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point, Polygon
from scipy.spatial.distance import cdist

# --------------------------
# Configuration & Paths
# --------------------------
DISTANCE = 13
CELL_SIZE = 8
NUM_ITERATIONS = 2  # Number of sliding iterations

# Input/Output paths (Ensure these match the outputs of the first script)
INPUT_SHP = f"/mnt/parscratch/users/acb20si/label_tree_shp/random_trees_32718_{DISTANCE}.shp"
EMBEDDING_PATH = r"data/embeddings/embeddings.npy"
LABEL_PATH = r"data/label/labels.npy"
COORD_PATH = r"data/embeddings/coords.npy"  # Extracted coordinates from the first script
OUTPUT_DIR = r"data/distance"

# --------------------------
# Utility Functions
# --------------------------
def load_data():
    """
    Load the shapefile and numpy arrays generated by the first script.
    Raises an error if the required coordinate or embedding files are missing.
    """
    if not (os.path.exists(EMBEDDING_PATH) and os.path.exists(COORD_PATH)):
        raise FileNotFoundError(
            "Embedding or coordinate files not found. "
            "Please run the first script to generate them."
        )

    random_trees = gpd.read_file(INPUT_SHP)
    embeddings = np.load(EMBEDDING_PATH)
    labels = np.load(LABEL_PATH)
    coords = np.load(COORD_PATH)  # Shape: [N, 2] containing (x, y) coordinates
    
    return random_trees, embeddings, labels, coords

def create_3x3_grid(center_point, cell_size=5.0):
    """
    Create a 3x3 grid (9 distinct bounding boxes) around a given center point.
    """
    x, y = center_point.x, center_point.y
    boxes = []
    
    # Iterate through grid offsets
    for i in range(-1, 2):      # y-axis offsets (-1, 0, 1)
        for j in range(-1, 2):  # x-axis offsets (-1, 0, 1)
            minx = x + (j * cell_size) - (cell_size / 2)
            maxx = x + (j * cell_size) + (cell_size / 2)
            miny = y - (i * cell_size) - (cell_size / 2)
            maxy = y - (i * cell_size) + (cell_size / 2)
            
            box_poly = Polygon([(minx, miny), (maxx, miny), (maxx, maxy), (minx, maxy)])
            boxes.append(box_poly)
            
    return boxes

def calculate_likelihood(box, target_label, embeddings, labels, coords):
    """
    Calculate the likelihood that a grid box contains the target tree species.
    It finds the nearest extracted coordinate to the box center and checks its label.
    """
    # 1. Calculate the distance from the box center to all available extracted coordinates
    box_center = np.array([[box.centroid.x, box.centroid.y]])
    distances = cdist(box_center, coords)
    
    closest_idx = np.argmin(distances)
    min_dist = distances[0, closest_idx]

    # 2. If the closest coordinate is too far (e.g., > CELL_SIZE), assume low confidence
    if min_dist > CELL_SIZE:
        return 0.0

    # 3. Check if the predicted label at that location matches the target label
    predicted_label = str(labels[closest_idx])
    
    # Return 1.0 if it's an exact match, otherwise 0.0
    return 1.0 if predicted_label == str(target_label) else 0.0

def process_slide_grid(current_points, embeddings, labels, coords, cell_size=5.0):
    """
    Execute one iteration of the sliding grid algorithm.
    Evaluates the 3x3 grid around each point and determines the new center or slide points.
    """
    new_centers = []
    new_slides = []
    
    # Identify the column containing the tree species/label information
    label_col = 'Tree' if 'Tree' in current_points.columns else current_points.columns[0]
    
    for _, row in current_points.iterrows():
        point = row.geometry
        target_label = row[label_col]
        
        # Create grid and check likelihood for each box
        boxes = create_3x3_grid(point, cell_size)
        checked_boxes = []
        
        for box in boxes:
            likelihood = calculate_likelihood(box, target_label, embeddings, labels, coords)
            if likelihood >= 0.5:
                checked_boxes.append(box)
                
        num_checked = len(checked_boxes)
        
        # Apply sliding rules based on the number of confident boxes
        if num_checked >= 3:
            # 3 or more matches -> Shift to the average center of matched boxes
            avg_x = sum([b.centroid.x for b in checked_boxes]) / num_checked
            avg_y = sum([b.centroid.y for b in checked_boxes]) / num_checked
            new_centers.append({'geometry': Point(avg_x, avg_y), label_col: target_label})
            
        elif 1 <= num_checked <= 2:
            # 1 to 2 matches -> Slide towards the matched boxes
            avg_x = sum([b.centroid.x for b in checked_boxes]) / num_checked
            avg_y = sum([b.centroid.y for b in checked_boxes]) / num_checked
            new_slides.append({'geometry': Point(avg_x, avg_y), label_col: target_label})
            
        else:
            # 0 matches -> Keep the current point as a slide point
            new_slides.append({'geometry': point, label_col: target_label})
            
    # Convert lists back to GeoDataFrames
    crs = current_points.crs
    gdf_centers = gpd.GeoDataFrame(new_centers, crs=crs) if new_centers else gpd.GeoDataFrame(columns=[label_col, 'geometry'], crs=crs)
    gdf_slides = gpd.GeoDataFrame(new_slides, crs=crs) if new_slides else gpd.GeoDataFrame(columns=[label_col, 'geometry'], crs=crs)
    
    return gdf_centers, gdf_slides

# --------------------------
# Main Execution
# --------------------------
def main():
    print("Loading data...")
    random_trees, embeddings, labels, coords = load_data()
    
    all_final_points = []
    current_slides = random_trees
    
    print(f"Starting sliding grid algorithm (Iterations: {NUM_ITERATIONS})...")
    
    for step in range(NUM_ITERATIONS):
        print(f"--- Step {step + 1} ---")
        if current_slides.empty:
            print("No slide points remaining. Ending loop.")
            break
            
        centers, current_slides = process_slide_grid(
            current_slides, 
            embeddings, 
            labels, 
            coords,
            cell_size=CELL_SIZE
        )
        
        if not centers.empty:
            all_final_points.append(centers)
            
        print(f"Generated: {len(centers)} Center points, {len(current_slides)} Slide points.")
    
    # Append any remaining slide points to the final results
    if not current_slides.empty:
        all_final_points.append(current_slides)
    
    # Consolidate and save
    if all_final_points:
        final_points_gdf = pd.concat(all_final_points, ignore_index=True)
        final_points_gdf = gpd.GeoDataFrame(final_points_gdf, crs=random_trees.crs)
        
        save_path = os.path.join(OUTPUT_DIR, f"slide_grid_results_d{DISTANCE}_cz{CELL_SIZE}.shp")
        os.makedirs(OUTPUT_DIR, exist_ok=True)
        
        final_points_gdf.to_file(save_path)
        print(f"\nAlgorithm finished. Total points saved: {len(final_points_gdf)}")
        print(f"Results saved to: {save_path}")
    else:
        print("\nAlgorithm finished. No points were generated.")

if __name__ == "__main__":
    main()